[package]
name = "patheticd"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.39"
derive_more = { version = "2", features = ["debug", "display"] }
hyprland = "0.3.13"
tokio = "1.45.1"
toml = "0.8.23"
